"""Common schemas exchanged between agents and providers."""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class RunRequest:
    """A normalized request for a domain model execution."""

    params: Dict[str, Any]
    requested_by: str = "user"
    correlation_id: Optional[str] = None


@dataclass
class RunArtifact:
    """A pointer to persisted outputs generated by model execution."""

    path: str
    artifact_type: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AnalysisRequest:
    """User question plus optional evidence references for analysis."""

    question: str
    artifacts: List[RunArtifact] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AnalysisResult:
    """Structured analysis output returned by analyzer agents."""

    metrics: Dict[str, Any]
    notes: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EvidenceChunk:
    """A retrieved context chunk from vector stores, documents, or logs."""

    text: str
    source: str
    score: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class KGFact:
    """A normalized knowledge-graph triple/edge payload."""

    subject: str
    predicate: str
    object: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentMessage:
    """A generic inter-agent message contract."""

    sender: str
    recipient: str
    message_type: str
    payload: Dict[str, Any] = field(default_factory=dict)
    correlation_id: Optional[str] = None

